/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author caue.seidel
 */
public class Entrada_Porcas extends javax.swing.JFrame {

    /**
     * Creates new form Entrada_Porcas
     */
    public Entrada_Porcas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bemvindo_tela_login2 = new javax.swing.JLabel();
        lbl_bemvindo_tela_login3 = new javax.swing.JLabel();
        lbl_bemvindo_tela_login4 = new javax.swing.JLabel();
        lbl_bemvindo_tela_login5 = new javax.swing.JLabel();
        TXT_Mossa_CadastroPorca = new javax.swing.JTextField();
        TxtDT_Entrada_CadastroPorca = new javax.swing.JFormattedTextField();
        TXT_Brinco_CadastroPorca = new javax.swing.JTextField();
        BTN_Cadastrar_CadastroPorca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bemvindo_tela_login2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_bemvindo_tela_login2.setText("Mossa");

        lbl_bemvindo_tela_login3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_bemvindo_tela_login3.setText("Data da entrada");

        lbl_bemvindo_tela_login4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_bemvindo_tela_login4.setText("Brinco");

        lbl_bemvindo_tela_login5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_bemvindo_tela_login5.setText("Cadastro Porca");

        TXT_Mossa_CadastroPorca.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        TXT_Mossa_CadastroPorca.setText("jTextField1");
        TXT_Mossa_CadastroPorca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_Mossa_CadastroPorcaActionPerformed(evt);
            }
        });

        TxtDT_Entrada_CadastroPorca.setText("DATE");
        TxtDT_Entrada_CadastroPorca.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N

        TXT_Brinco_CadastroPorca.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        TXT_Brinco_CadastroPorca.setText("jTextField1");
        TXT_Brinco_CadastroPorca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_Brinco_CadastroPorcaActionPerformed(evt);
            }
        });

        BTN_Cadastrar_CadastroPorca.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        BTN_Cadastrar_CadastroPorca.setText("CADASTRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_Brinco_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bemvindo_tela_login4)
                    .addComponent(lbl_bemvindo_tela_login2)
                    .addComponent(TXT_Mossa_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtDT_Entrada_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_bemvindo_tela_login3))
                        .addGap(411, 411, 411))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_bemvindo_tela_login5)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTN_Cadastrar_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_bemvindo_tela_login5)
                .addGap(57, 57, 57)
                .addComponent(lbl_bemvindo_tela_login2)
                .addGap(28, 28, 28)
                .addComponent(TXT_Mossa_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lbl_bemvindo_tela_login4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_Brinco_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lbl_bemvindo_tela_login3)
                .addGap(30, 30, 30)
                .addComponent(TxtDT_Entrada_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(BTN_Cadastrar_CadastroPorca, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_Mossa_CadastroPorcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_Mossa_CadastroPorcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_Mossa_CadastroPorcaActionPerformed

    private void TXT_Brinco_CadastroPorcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_Brinco_CadastroPorcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_Brinco_CadastroPorcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada_Porcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada_Porcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada_Porcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada_Porcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada_Porcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cadastrar_CadastroPorca;
    private javax.swing.JTextField TXT_Brinco_CadastroPorca;
    private javax.swing.JTextField TXT_Mossa_CadastroPorca;
    private javax.swing.JFormattedTextField TxtDT_Entrada_CadastroPorca;
    private javax.swing.JLabel lbl_bemvindo_tela_login2;
    private javax.swing.JLabel lbl_bemvindo_tela_login3;
    private javax.swing.JLabel lbl_bemvindo_tela_login4;
    private javax.swing.JLabel lbl_bemvindo_tela_login5;
    // End of variables declaration//GEN-END:variables
}
