/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import tools.CaixaDeDialogo;

/**
 *
 * @author CauÊSeidel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);//JANELA MAXIMIZADA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuUsuarios_tela_principal1 = new javax.swing.JMenuItem();
        menuUsuarios_tela_principal4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuUsuarios_tela_principal3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuUsuarios_tela_principal2 = new javax.swing.JMenuItem();
        menuUsuarios_tela_principal6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuUsuarios_tela_principal7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuUsuarios_tela_principal5 = new javax.swing.JMenuItem();
        menuSair_tela_principal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu2.setText("Cadastros");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jMenu2.setIconTextGap(20);

        menuUsuarios_tela_principal1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal1.setText("Usuários");
        menuUsuarios_tela_principal1.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal1ActionPerformed(evt);
            }
        });
        jMenu2.add(menuUsuarios_tela_principal1);

        menuUsuarios_tela_principal4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal4.setText("Entrada Porcas");
        menuUsuarios_tela_principal4.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal4ActionPerformed(evt);
            }
        });
        jMenu2.add(menuUsuarios_tela_principal4);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Abate");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jMenu1.setIconTextGap(20);

        menuUsuarios_tela_principal3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal3.setText("Abate");
        menuUsuarios_tela_principal3.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal3ActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuarios_tela_principal3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Agendamento");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jMenu3.setIconTextGap(20);

        menuUsuarios_tela_principal2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal2.setText("Datas de parto");
        menuUsuarios_tela_principal2.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal2ActionPerformed(evt);
            }
        });
        jMenu3.add(menuUsuarios_tela_principal2);

        menuUsuarios_tela_principal6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal6.setText("Anotações Gerais");
        menuUsuarios_tela_principal6.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal6ActionPerformed(evt);
            }
        });
        jMenu3.add(menuUsuarios_tela_principal6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Caliper");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jMenu4.setIconTextGap(20);

        menuUsuarios_tela_principal7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal7.setText("Caliper");
        menuUsuarios_tela_principal7.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal7ActionPerformed(evt);
            }
        });
        jMenu4.add(menuUsuarios_tela_principal7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Registros");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jMenu5.setIconTextGap(20);

        menuUsuarios_tela_principal5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuUsuarios_tela_principal5.setText("Partos");
        menuUsuarios_tela_principal5.setBorder(new javax.swing.border.MatteBorder(null));
        menuUsuarios_tela_principal5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios_tela_principal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarios_tela_principal5ActionPerformed(evt);
            }
        });
        jMenu5.add(menuUsuarios_tela_principal5);

        jMenuBar1.add(jMenu5);

        menuSair_tela_principal.setText("Sair");
        menuSair_tela_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSair_tela_principal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuSair_tela_principal.setIconTextGap(20);
        menuSair_tela_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair_tela_principalActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair_tela_principal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSair_tela_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair_tela_principalActionPerformed
        try{
            boolean resposta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Deseja mesmo Sair", "confirmação", 'p');
            if(resposta){
                System.exit(0);
            }
            
        }catch(Exception e){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao sair");}
    }//GEN-LAST:event_menuSair_tela_principalActionPerformed

    private void menuUsuarios_tela_principal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal1ActionPerformed
        Cadastro_Usuario tela = new Cadastro_Usuario();
        tela.setVisible(true);
    }//GEN-LAST:event_menuUsuarios_tela_principal1ActionPerformed

    private void menuUsuarios_tela_principal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal2ActionPerformed
        AgendamentoPartos telaAG = new AgendamentoPartos();
        telaAG.setVisible(true);
    }//GEN-LAST:event_menuUsuarios_tela_principal2ActionPerformed

    private void menuUsuarios_tela_principal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal5ActionPerformed
        Registro_parto telaR = new Registro_parto();
        telaR.setVisible(true);
    }//GEN-LAST:event_menuUsuarios_tela_principal5ActionPerformed

    private void menuUsuarios_tela_principal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal4ActionPerformed
        Entrada_Porcas telaE = new Entrada_Porcas();
        telaE.setVisible(true);
    }//GEN-LAST:event_menuUsuarios_tela_principal4ActionPerformed

    private void menuUsuarios_tela_principal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal6ActionPerformed
        dispose();
    }//GEN-LAST:event_menuUsuarios_tela_principal6ActionPerformed

    private void menuUsuarios_tela_principal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal3ActionPerformed
        Abate telaA = new Abate();
        telaA.setVisible(true);
    }//GEN-LAST:event_menuUsuarios_tela_principal3ActionPerformed

    private void menuUsuarios_tela_principal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarios_tela_principal7ActionPerformed
       Caliper telaC = new Caliper();
       telaC.setVisible(true);
    }//GEN-LAST:event_menuUsuarios_tela_principal7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuSair_tela_principal;
    private javax.swing.JMenuItem menuUsuarios_tela_principal1;
    private javax.swing.JMenuItem menuUsuarios_tela_principal2;
    private javax.swing.JMenuItem menuUsuarios_tela_principal3;
    private javax.swing.JMenuItem menuUsuarios_tela_principal4;
    private javax.swing.JMenuItem menuUsuarios_tela_principal5;
    private javax.swing.JMenuItem menuUsuarios_tela_principal6;
    private javax.swing.JMenuItem menuUsuarios_tela_principal7;
    // End of variables declaration//GEN-END:variables
}
